### PR TITLE
#161049094 A store attendant should be able to search and Add Items to Cart

### PR DESCRIPTION
**Pull request by sharkdevs**
**What does this PR do?**
Provides an Interface for the Store attendant to search item, add to the cart and checkout

**Description of the Task to be completed**

1. Display Items to be sold.
2. Searching for an Item from the inventory.
3. Adding a desired item to the cart.
4. Checking out.

**How should it be manually Tested**
1. clone the following repository to your working folder: `https://github.com/sharkdevs/Store-Manager/`
2. Navigate to `/ui/cart.html` and open it on a browser.

**What are the relevant pivotal tracker stories**
#161049094

**Screen Shots**

screenshot_2018-10-10 store manager - shopping cart

2cart

screenshot_2018-10-10 store manager - shopping cart 1

### CODE REVIEW

**Comment by Nicanor008** [comment]
Great UI, nice work. You can add a button to add to cart on each and every product

**Comment by sharkdevs** [comment]
> 
> 
> Great UI, nice work. You can add a button to add to cart on each and every product

It goes to the cart on clicking the product. How about that?

**Comment by jomasim** [comment]
Great stuff. I would like you to redesign the products container ensure they are visible, fixed in size , they align next to each other so that products dont look like they are thrown over the page.

**Comment by sharkdevs** [comment]
> 
> 
> Great stuff. I would like you to redesign the products container ensure they are visible, fixed in size , they align next to each other so that products dont look like they are thrown over the page.

Thanks.. will consider that, though I wanted to have a hover effect so that it gives a background on hover. thanks.

**Comment by boltonotieno** [comment]
The UI design is nice...good work

**Comment by Arusey** [comment]
Great UI..looks perfect

**Pull request merged**
