### PR TITLE
#161048644 User should be able to Login the system

### PR DESCRIPTION
**Pull request by sharkdevs**
**What does this PR Do?**
Provides an interface where users can log into the store management system using their emails and passwords.
**Description of Tasks to be completed**

- User Login form for user to sign in

- Landing Page User interface

**How should this be manually tested?**
To test the work here, follow the following steps.

1. Create a working folder on your desktop or preferred location.
2. open `git terminal` and navigate to the working folder that you created.
3. Type the following `git clone https://github.com/sharkdevs/Store-Manager`
4. Navigate to the `UI` directory and open `index.html` in a preferred browser.

**What are the relevant pivotal tracker stories?**
story-id: #161048644

**Screen shots**
screenshot_2018-10-09 store manager

### CODE REVIEW

**Comment by Allan690** [comment]
Nice work, brilliant interface there

**Comment by Georgeygigz** [comment]
Nyc interface bro

**Comment by jomasim** [comment]
Good work meshack! I hope you didnt use any font awesome or bootstrap somewhere.The instructions prohibit us from using any external library.

**Comment by ogol254** [comment]
Nice work

**Comment by waracci** [comment]
Great UI, looks very professional.

**Pull request merged**
